//
//  Constants.swift
//  Momtaz-IOS
//
//  Created by Mohamed Abd Elhakam on 05/12/2024.
//

import Foundation

class Constants{
    static let cancel = "Cancel"
    static let ok = "OK"
    static let yes = "Yes"
    static let warning = "Warning !!"
    static let phoneNumber = "Phone Number"
    static let password = "Password"
    static let fullName = "Full Name"
    static let confirmPassword = "Confirm Password"
    static let noInternetConnection = "No internet connection"
    static let loading = "Loading..."
    static let success = "Success"
    static let error = "Error"
    static let save = "Save"
    static let from = "From"
    static let to = "To"
    static let fromHour = "From hour:"
    static let toHour = "To hour:"
    
    //MARK: Auth constants
    static let login = "LogIn"
    static let loginHeadText = "Enter your account"
    static let loginSubHeadText = "Please add your information so we continue"
    static let notHaveToken = "not have token please try in another time"
    static let FailedToLogin = "Your email or password is incorrect"
    static let forgetPassword = "Forget Password?"
    static let notHaveAcccount = "Not have account? SignUp"
    
    static let signup = "SignUp"
    static let signUpHeadText = "Create new account"
    static let signUpSubHeadText = "Please add your information so we continue"
    static let termsAndConditions = "I accepted all terms and conditions of platforms"
    static let alreadyHaveAccount = "Do you already have account? LogIn"
    
    
    //MARK: work agenda
    static let workAgendaHeadText = "Work Agenda"
    static let workAgendaSubHeadText = "View and manage all your upcoming and previous classes easily and the ability to sync the calendar with your appointment"
    static let date = "Date"
    static let noLessonHeadText = "There are no lessons today"
    static let enjoyTime = "Enjoy your free time!"
    static let lesssonCancelled = "The class has been cancelled"
    static let name = "Name"
    static let location = "Location"
    static let level = "Level"
    static let subject = "Subject"
    static let hour = "Hour"
    static let minute = "Minute"
    static let day = "Day"
    static let parent = "Parent"
    static let price = "Price"
    static let callParent = "Call Parent"
    static let call = "Call"
    static let messageParent = "Message Parent"
    static let addReview = "Add Review"
    static let showReview = "Show Review"
    static let changeLessonDate = "Change Lesson Date"
    static let deleteLesson = "Delete Lesson"
    static let warningMessageToDeleteLesson = "You will delete student lesson, are you sure?"
    static let lessonDeleteSuccessfully = "Lesson Deleted Successfully"
    static let failedDeleteLesson = "Error while Deleting Lesson"
    static let invailedSelectedDay = "This selected day is an off day. Please choose working day."
    static let notDurationAvailable = "No duration available"
    static let monthly = "Monthly"
    static let oneClass = "Individual class"
    static let updateDate = "Update Date"
    static let warningMessageFromUpdateLessonDate = "You will update student lesson date, are you sure?"
    static let updateLessonDateSuccessfully = "Lesson date updated successfully"
    static let updateLessonDateFailed = "Error while updating Lesson date"
    static let noHavePhoneNumber = "Not have phone number to call parent"
    static let primarySchool = "Primary school"
    static let secondarySchool = "Secondary school"
    static let highSchool = "High school"
    static let firstPrimarySchool = "First year of primary school"
    static let secondaryPrimarySchool = "Second year of primary school"
    static let thirdPrimarySchool = "Third year of primary school"
    static let fourthPrimarySchool = "Fourth year of primary school"
    static let fifthPrimarySchool = "Fifth year of primary school"
    static let sixthPrimarySchool = "Sixth year of primary school"
    static let firstSecondarySchool = "First year of Secondary school"
    static let secondSecondarySchool = "Second year of Secondary school"
    static let thirdSecondarySchool = "Third year of Secondary school"
    static let firstHighSchool = "First year of high school"
    static let secondaryHighSchool = "Second year of high school"
    static let thirdHighSchool = "Third year of high school"
    
    //MARK: Review page
    static let showReviewHeadText = "Review Informations"
    static let knowledgeOfSubject = "student knowledge of the scientific subject:"
    static let studentComprehensionAbility = "Student comprehension ability:"
    static let studentCommitment = "The extent of the student commitment:"
    static let overAllAssessment = "overall assessment:"
    static let note = "Note"
    static let addNoteMessage = "Please add your notes about the class here."
    
    static let addReviewHeadText = "Student evaluation during the class"
    static let addReviewSubHeadText = "The evaluation will help us analyze the results and create reports that will help you know the student condition."
    static let studentDetails = "Student Details"
    static let studentEvaluation = "Student evaluation"
    static let ratingGroup1Title = "The student's understanding of the subject matter."
    static let ratingGroup2Title = "Student comprehension ability."
    static let ratingGroup3Title = "The extent of the student commitment."
    static let ratingGroup4Title = "General assessment of the share."
    static let good = "Good"
    static let notGood = "Not Good"
    static let addAllStudentReportDetails = "Please enter all student evaluations"
    static let failedToAddStudentReport = "error while add student report"
    static let addStudentReportSuccessfully = "student report added successfully"
    
    
    //MARK: Reservation page
    static let reservationHeadText = "Reservation"
    static let reservationSubHeadText = "You can know and control your reservations completely."
    static let onProgress = "On Progress"
    static let cancelled = "Cancelled"
    static let finished = "Finished"
    static let notHaveProgressBookingHead = "You don't have any progress bookings scheduled at the moment. Please set up sessions to track student growth and provide timely feedback"
    static let notHaveCancelledBooking = "You don't have any canceled bookings at the moment. Please check your schedule for any changes or cancellations."
    static let notHaveFinishedBooking = "You don't have any finished bookings at the moment. Please complete your sessions to ensure progress is tracked and feedback is provided."
    static let classHistory = "Class History"
    static let classHistoryPerWeek = "Classes History (per week)"
    static let classDuration = "Class Duration"
    static let eductionalLevel = "Eductional Level"
    static let studentLocation = "Student Location"
    static let showBill = "Show Bill"
    static let deletebooking = "Delete Booking"
    static let currency = "SAR"
    static let billInformations = "Bill Informations"
    static let classPrice = "Class Price"
    static let oneClasses = "class"
    static let classes = "classes"
    static let total = "Total"
    static let classPerWeek = "Class per week"
    static let warningMessageToDeleteBooking = "You will delete Booking, are you sure?"
    static let bookingDeleteSuccessfully = "Booking Deleted Successfully"
    static let failedDeleteBooking = "Error while Deleting Booking"
    
    //MARK: students page
    static let StudentsPageSubHeadText = "Manage your students completely, including reports, exams, appointments, and more"
    static let yourStudents = "Your Students"
    static let student = "Student"
    static let totalStudentsNumber = "Total number of students"
    static let newStudents = "New Students"
    static let newStudentsInThisMonth = "New students in this month"
    static let eductionalStage = "Eductional Stage"
    static let classRoom = "Classroom"
    static let notHaveStudents = "There are no students"
    
    
    
}
